### ISSUE TITLE
Can I use Redux-Thunk with Drizzle?

### ISSUE THREAD

**Issue by hackingbeauty** [ConsenSys-archive/drizzle-legacy#120] opened 2018-10-01 22:47 UTC
I would like to use Redux-Thunk and not Redux-Saga in my project.  Do I have to use Redux-Saga in order to use Drizzle?

**Comment by adrianmcli** [comment] 2018-10-24 22:37
Duplicate of #121

**Closed as completed by adrianmcli** 2018-10-24 22:37 UTC
